name: software

description: The Ubuntu Software Store made with Flutter.

publish_to: "none"

version: 0.2.9-alpha

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  appstream: ^0.2.8
  async: ^2.10.0
  badges: ^2.0.3
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  connectivity_plus: ^2.3.1
  crypto: ^3.0.2
  data_size: ^0.2.0
  dbus: ^0.7.8
  desktop_notifications: ^0.6.3
  file: ^6.1.2
  file_selector: ^0.8.4+1
  file_selector_linux: ^0.0.2+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.0
  glib: 0.0.1
  gtk_application: ^0.0.3
  handy_window: ^0.3.0
  intl: ^0.18.0
  launcher_entry: ^0.1.0
  liquid_progress_indicator:
    git:
      url: https://github.com/ubuntu-flutter-community/liquid_progress_indicator
      ref: fdeb8de
  meta: ^1.7.0
  odrs: ^0.0.1
  package_info_plus: ^4.0.0
  packagekit: ^0.2.6
  palette_generator: ^0.3.3
  path: ^1.8.2
  provider: ^6.0.2
  quiver: ^3.1.0
  safe_change_notifier: ^0.2.0
  shimmer: ^2.0.0
  snapcraft_launcher: ^0.1.0
  snapd: 0.4.8
  snowball_stemmer: ^0.1.0
  synchronized: ^3.0.0+3
  ubuntu_service: ^0.2.0
  ubuntu_session: ^0.0.2
  url_launcher: ^6.1.2
  version: ^3.0.2
  xdg_icons: ^0.0.1
  yaru: ^0.5.5
  yaru_colors: ^0.1.6
  yaru_icons: ^1.0.3
  yaru_widgets: ^2.1.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/contributors.md
    - assets/software.desktop
    - assets/software.png
