name: analyze

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: analyze
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.7.x"

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze
